#!/bin/sh
export ROOT="/root"

fail(){
	echo "[ERROR] $1"
	echo "Rebooting in 5 seconds"
	sleep 5
	reboot
}
mount none -t proc /proc
mount none -t sysfs /sys
busybox mdev -s
mkdir /tmp
echo "----------- Ubuntu Touch 1.0 ------------" >/dev/kmsg
echo "| Custom initrd and porting by Matsca09 |" >/dev/kmsg
echo "| If you like my work, please donate :) |" >/dev/kmsg
echo "-----------------------------------------" >/dev/kmsg
echo "-> Mounting /sdcard and Ubuntu image"
mount /dev/mmcblk0p3 /sdcard || fail "Cannot mount internal SD!" >/dev/kmsg
mount -o rw,loop /sdcard/ubuntu/system.img $ROOT || fail "Cannot mount loop image!" >/dev/kmsg

# Some adapted code from official Ubuntu Touch initrd
if [ ! -e $ROOT/data ]; then
	mkdir $ROOT/data
fi
if [ ! -e $ROOT/android ]; then
	mkdir $ROOT/android
fi
if [ ! -e $ROOT/system ]; then
	mkdir $ROOT/system
fi
if [ ! -e $ROOT/vendor ]; then
	mkdir $ROOT/vendor
fi
mount /dev/mmcblk0p2 $ROOT/data || fail "Cannot mount data!"
mount -o rw,size=4096 -t tmpfs none $ROOT/android
mount -o rw,nosuid,noexec,relatime,mode=755 -t tmpfs tmpfs $ROOT/run

echo "-> Doing some boooooring things"
for dir in system-data system-data/dbus \
	system-data/network-manager/connections \
	system-data/network-manager/lib \
	system-data/log system-data/log/upstart userdata android-data; do
		mkdir -p $ROOT/data/$dir
done
if [ ! -d $ROOT/data/phablet ]; then
	ln -s $ROOT/home/phablet $ROOT/data/phablet
fi

mkdir $ROOT/android/system
mount -o ro /dev/mmcblk0p1 $ROOT/android/system || fail "Cannot mount system!"
mount -o bind $ROOT/android/system $ROOT/system
mount -o bind $ROOT/system/vendor $ROOT/vendor

mkdir $ROOT/android/data
mount -o bind /data $ROOT/android/data
device=$(grep ^ro.product.device= $ROOT/android/system/build.prop |sed -e 's/.*=//')
if [ -n "$device" ]; then
	mount --bind $ROOT/usr/lib/lxc-android-config/70-$device.rules $ROOT/lib/udev/rules.d/70-android.rules
fi
[ -e /system/lib/modules ] && mount --bind /system/lib/modules /lib/modules
mount --bind $ROOT/usr/lib/lxc-android-config/image-fstab $ROOT/etc/fstab

# End adapted code

# RILD Patch
mkdir $ROOT/android/efs
chmod 0755 $ROOT/android/efs
chown radio:radio $ROOT/android/efs
mount -t yaffs2 /dev/mtdblock6 $ROOT/android/efs || echo "WARNING: Cannot mount efs, phone functions will not work!!!!" >/dev/kmsg

echo "-> Everything ready! Switching root and starting Ubuntu Touch (finally :D)"

mount none -t proc $ROOT/proc
mount none -t sysfs $ROOT/sys
mount none -t devtmpfs $ROOT/dev
# Mount internal storage in a folder into UbuTouch default user home dir (phablet)
if [ ! -e $ROOT/home/phablet/sdcard ]; then
	mkdir $ROOT/home/phablet/sdcard
fi
mount /dev/mmcblk0p3 /$ROOT/home/phablet/sdcard
swapon $ROOT/SWAP.swap
#exec run-init $ROOT /sbin/init "$@" <$ROOT/dev/console > $ROOT/dev/console 2>&1
exec switch_root $ROOT /sbin/init "$@" <$ROOT/dev/console > $ROOT/dev/console 2>&1


